name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github-artifactory'
      PLATFORM_REPO: 'proj1-npm-virtual'
      JFROG_CLI_BUILD_PROJECT: 'proj1'
      JFROG_CLI_LOG_LEVEL: 'DEBUG'
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v4
              
       - name: Setup Node npm
         uses: actions/setup-node@v4
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:
           # JF_USER: ${{ secrets.JF_USER }}
           # JF_PASSWORD: ${{ secrets.JF_ACCESS_TOKEN }}
           JF_URL: ${{ vars.JF_URL }}
           JF_PROJECT: ${{ vars.JF_PROJECT }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: Set CLI Config
         run: jf npm-config --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO
           
       - name: Install Dependencies
         run: jf npm install
           
       - name: Run tests
         run: npm test
         
       - name: Publish
         run: jf npm publish
         
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish
       - name: Scan Build
         run: |          
          jf bs --fail=false
