name: "JFrog-GitHub NPM Publish OIDC Integration"
on: 
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "スキャン対象ブランチ"
        required: true
        default: "main"
        type: string
# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 【利用者編集】スキャン対象ブランチ
        branch: ["main"]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ inputs.branch || matrix.branch }}

      - uses: jfrog/frogbot@eb4b14765ca0e7a2944f6c80c2d659ff7e9f9869 # Actionの固定SHA（実行バイナリーはwith.versionで指定）
        with:
          oidc-provider-name: 'github-artifactory'
          oidc-audience: 'jfrog-github'
          # 【利用者編集】Frogbotバイナリのバージョンを固定する場合はコメント解除
          version: '3.8.0'
        env:
          JFROG_CLI_LOG_LEVEL: DEBUG
          CI: "true"
          JF_URL:              ${{ vars.JF_URL }}
          JF_GIT_TOKEN:        ${{ secrets.GITHUB_TOKEN }}
          #JF_GIT_API_ENDPOINT: "https://api.ghe.example.com"
          JF_GIT_BASE_BRANCH:  ${{ inputs.branch || matrix.branch }}
          JF_PROJECT:          'proj1'
